image: docker:latest

services:
  - name: docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:
  tags:
    - docker-atp
  script:
    - docker build -t enki .
    - docker run --privileged enki /bin/bash -c "./scripts/create-net.sh && python3 -m pytest -s ."
