image: docker:latest

services:
  - docker:dind

test:
  stage: test
  tags:
    - docker-atp
  script:
    - docker build -t enki .
    - docker run --privileged enki /bin/bash -c "./scripts/create-net.sh && python3 -m pytest ."
